---
# Configures the CLI PHP SAPI

- name: configure PHP CLI SAPI configuration file - CentOS
  ini_file:
       dest=/etc/php.ini
    section='{{ item.0.section }}'
     option='{{ item.1.option }}'
      value='{{ item.1.value }}'
  with_subelements:
    - "{{ php7_sapi_cli_options }}"
    - options
  when: ansible_distribution == "CentOS"

- name: configure PHP CLI SAPI configuration file - Ubuntu
  ini_file:
       dest=/etc/php/7.0/cli/php.ini
    section='{{ item.0.section }}'
     option='{{ item.1.option }}'
      value='{{ item.1.value }}'
  with_subelements:
    - "{{ php7_sapi_cli_options }}"
    - options
  when: ansible_distribution == "Ubuntu"
