---
# Install Zend OpCache extension

# The OpCache extension is already enabled on Ubuntu when using non-system and system only package sources

# If using non-system sources (preferred)

- name: install OpCache extension from non-system sources - CentOS
  yum:
             pkg={{ item }}
    update_cache=yes
           state=present
  with_items:
    - php70w-opcache
  when: ansible_distribution == "CentOS" and
    (BARC_use_non_system_package_sources == true or BARC_use_non_system_package_sources == 'True')

# If using system-sources only (non-supported)

- fail: msg="PHP 7 is not availble from system only package sources - aborting."
  when: BARC_use_non_system_package_sources == false or BARC_use_non_system_package_sources == 'False'
