---
# Install the PHP 7 language

# If using non-system sources (preferred)

- name: install prerequisites for installing PPAs - Ubuntu
  apt:
                 pkg={{ item }}
        update_cache=yes
    cache_valid_time=3600
               state=present
  with_items:
    - software-properties-common
  when: BARC_use_non_system_package_sources == true or BARC_use_non_system_package_sources == 'True'

- name: add PHP 7 PPA - Ubuntu
  apt_repository:
    repo='ppa:ondrej/php'
    state=present
  when: BARC_use_non_system_package_sources == true or BARC_use_non_system_package_sources == 'True'

- name: install PHP 7 - Ubuntu
  apt:
                 pkg={{ item }}
        update_cache=yes
    cache_valid_time=3600
               state=present
  with_items:
    - php7.0-cli
  when: BARC_use_non_system_package_sources == true or BARC_use_non_system_package_sources == 'True'

# If using system-sources only (non-supported)

- fail: msg="PHP 7 is not availble from system only package sources - aborting."
  when: BARC_use_non_system_package_sources == false or BARC_use_non_system_package_sources == 'False'
