---
# Install XDebug extension

# If using non-system sources (preferred)

# The PHP 7 XDebug package for CentOS is currently missing from the webtatic repository and so cannot be installed
# It is therefore skipped until this is resolved

# - name: install XDebug extension from non-system sources - CentOS
#   yum:
#              pkg={{ item }}
#     update_cache=yes
#            state=present
#   with_items:
#     - php70w-pecl-xdebug
#   when: ansible_distribution == "CentOS" and
#     (BARC_use_non_system_package_sources == true or BARC_use_non_system_package_sources == 'True')

- name: install XDebug extension from non-system sources - Ubuntu
  apt:
                 pkg={{ item }}
        update_cache=yes
    cache_valid_time=3600
               state=present
  with_items:
    - php-xdebug
  when: ansible_distribution == "Ubuntu" and
    (BARC_use_non_system_package_sources == true or BARC_use_non_system_package_sources == 'True')

# If using system-sources only (non-supported)

- fail: msg="PHP 7 is not availble from system only package sources - aborting."
  when: BARC_use_non_system_package_sources == false or BARC_use_non_system_package_sources == 'False'
